### ISSUE TITLE
allow viewing the description of a book

### ISSUE THREAD

**Issue by gnur** [gnur/booksing#5]
Add some mechanism to (safely) display the description of the book in the interface.

**Comment by pgaskin** [comment]
If you figure this out, I would be happy to include this in mine because I have this issue too. Some of my books have unclosed tags in the description, which ruins the rest of the page.

I was thinking about putting the description in an iframe, but that would only be slightly better, and would cause issues with long descriptions.

The biggest problem is that I cannot find any good library for HTML cleaning in pure go.

Good luck with this issue, and I would be happy to help.

P.S. You should add your name as another line in the license.

**Comment by gnur** [comment]
I added it in <pre> tags, does not look pretty but it does work :)
